[package]
name = "axum-lambda"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

axum = "0.5.6"
lambda_runtime = "0.5.1"
lambda_http = "0.5.1"

hyper = "0.14.18"

tokio = { version = "1.0", features = ["rt"] }

tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.2", features = ["cors", "compression-gzip"] }
tower-service = "0.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
